### ISSUE TITLE
Some question for HIDDEN projects

### ISSUE THREAD

**Issue by ZYH-cu** [lantchou/entropy-calculator#1]
Hi,
I happened to see you working on the pytorch version of HIDDEN, and I met some problems reproducing Hidden projec,resulting in a high error rate and poor image quality.
May I ask have you reproduced a acceptable result with combine noise?
Thanks a lot.

**Comment by lantchou** [comment]
Hi, my research was part of my master's thesis. Here's a link to the PDF, hope it helps: https://we.tl/t-EqryNFA7Ml

**Comment by ZYH-cu** [comment]
Really thanks for your sharing.
I also achieved similar results when facing a single attack，It seems that this project is effective, it just needs to find a appropriate combination of noise.
Thanks a lot.
